name: Approved actions operations

on:
  workflow_dispatch:
    inputs:
      operation:
        description: "Operation to perform. ex: update, add"
        required: true
        type: string
      action:
        description: "Single action to add. ex: actions/checkout"
        required: false
        type: string
      reason:
        description: "Business reason for the new action."
        required: false
        type: string

jobs:
  actions-operation:
    name: "Approved actions operations"
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    env:
      _ACTION: ${{ inputs.action }}
    steps:
      - name: Get actor
        id: get-actor
        run: 'echo "Actor: ${{ github.actor }}"'

      - name: Check for action input
        if: ${{ inputs.operation == 'add' && !env._ACTION }}
        run: echo "Action input is required for operation 'add'" && exit 1

      - name: Check for business reason
        if: ${{ inputs.operation == 'add' && !inputs.REASON }}
        run: echo "Business reason is required for operation 'add'" && exit 1

      - name: Create PR
        id: create-pr
        env:
          GH_TOKEN: ${{ github.token }}
          TITLE: "Update/Add bwwl approved actions${{ inputs.operation == 'add' && env._ACTION != '' && format(' for {0}', env._ACTION) || '' }}"
          REASON: "${{ inputs.operation == 'add' && format('\n## Business Reason\n    {0}\n', inputs.REASON) || '' }}"
        run: |
          echo gh pr create --title "$TITLE" \
            --base "main" \
            --head "${{ env.BRANCH_NAME }}" \
            --label "version:patch" \
            --label "automated pr" \
            --body "
              ## Type of change
              - [ ] Bug fix
              - [ ] New feature development
              - [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
              - [ ] Build/deploy pipeline (DevOps)
              - [ ] Other
              $REASON
              ## Description
              - This PR updates the approved actions for the Bitwarden Workflow Linter."
