# Publish GitHub workflow artifacts tutorial example
name: Github toJSON Test
on:
  workflow_dispatch:
  push:

permissions: {}

jobs:
  github-actions-environment-variables-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check toJSON strings
        env:
          TEST: ${{ github.event.workflow_run.pull_requests[0].head.ref }}
          TEST_JSON: ${{ toJSON(github.event.workflow_run.pull_requests[0].head.ref) }}
        run: echo "$TEST\n$TEST_JSON"
